services:
  - type: web
    name: moneydesk
    env: node
    plan: free
    buildCommand: ""
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: REQUIRE_DATABASE_URL
        value: true
